### ISSUE TITLE
0.6 callbacks meta-issue

### ISSUE THREAD

**Issue by mlubin** [JuliaOpt/JuMP.jl#230]
Some TODOs I think should be done for 0.6:
- [x] control over when lazy constraint callback is called (#154)
- [ ] more solve statistics (JuliaOpt/MathProgBase.jl#19)
- [x] clarification of `cbgetobj` and related methods (JuliaOpt/MathProgBase.jl#23)
- [x] add unit tests for providing bad solutions in heuristic callback (e.g. JuliaOpt/GLPKMathProgInterface.jl#12) (#248)
