### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by IainNZ** [JuliaOpt/JuMP.jl#40]
## Documentation (@IainNZ @mlubin @joehuchette)
- [x] Figure out platform (@mlubin)
- [x] Do it!
- [x] Lots of examples
## General Infrastructure
- [x] Parametric affine expressions
- [ ] More regular testing on Windows
## Problem modification
- [ ] Determine where the column-wise problem representation is kept
- [ ] Add methods to JuMP
- [ ] Make sure all the interfaces are working
- [ ] Develop example, e.g. column/row generation
- [ ] Speculative: automatic DW/LR/Benders reformulations ala Dip/Dippy
## Nonlinear
- [ ] IPOPT.jl interface
- [ ] Store the expression trees with the model
- [ ] Syntax of adding a NL constraint
- [ ] Integrate NLTester code into JuMP
- [ ] Factor out/share chain rule stuff with rest of Julia package ecosystem
- [ ] Tests
- [ ] Document
## Robust (@IainNZ)
- [x] Complete overloads for Uncertain/UAffExpr/FullAffExpr (2013/9/21)
- [ ] Create solve(m::RobustModel, solveMethod::Symbol)
- [ ] Implement reformulation
- [ ] Implement cutting plane
- [ ] Allow user to give initial cut set
- [ ] Allow variables to be defined as affinely adaptive
- [ ] Allow variables to be defined as finitely adaptive (Iain research related)
## Disjunctive (@mlubin @joehuchette)
- [ ] Speculate on what this looks like
## Other ideas
- [ ] OpenSolver SolverStudio integration on Windows (@IainNZ)
- [ ] SDPs
